version:
  label: develop
  isBeta: true
  usesBetaData: false
  officialUrl: "https://nomad-lab.eu/prod/v1/gui"

image:
  pullPolicy: "Always"

proxy:
  external:
    host: "nomad-lab.eu"

ingress:
  enabled: true

app:
  worker: 2

gui:
  debug: true

worker:
  replicas: 1
  routing: "queue"
  # request and limit in GB, good prod sizes are 64, 420
  memrequest: 1

elastic:
  host: elasticsearch.elasticsearch-7.svc.cluster.local

mongo:
  host: mongodb://mongodb-0.mongo.mongodb.svc.cluster.local,mongodb-1.mongo.mongodb.svc.cluster.local,mongodb-2.mongo.mongodb.svc.cluster.local/?replicaSet=rs0

logstash:
  host: logstash.elk.svc.cluster.local

dbname: nomad_dev_v1

keycloak:
  serverUrl: "https://nomad-lab.eu/fairdi/keycloak/auth/"
  serverExternalUrl: "https://nomad-lab.eu/fairdi/keycloak/auth/"
  passwordSecret: "nomad-keycloak-password"
  realmName: "fairdi_nomad_prod"
  clientId: "nomad_public"
  admin_user_id: "82efac55-6187-408c-8027-b98580c0e1c5"

volumes:
  prefixSize: 1
  public: /nomad/fairdi/dev/v1/fs/public
  staging: /nomad/fairdi/dev/v1/fs/staging
  north_home: /nomad/fairdi/dev/v1/fs/north/users
  tmp: /nomad/fairdi/dev/v1/fs/tmp
  nomad: /nomad

north:
  enabled: true
  hubServiceApiTokenSecret: "nomad-hub-service-api-token"

jupyterhub:
  fullnameOverride: null
  nameOverride: "north"
  hub:
    baseUrl:
    db:
      type: sqlite-memory
    config:
      GenericOAuthenticator:
        client_id: nomad_public
        oauth_callback_url: https://nomad-lab.eu/fairdi/nomad/latest/north/hub/oauth_callback
        authorize_url: https://nomad-lab.eu/fairdi/keycloak/auth/realms/fairdi_nomad_prod/protocol/openid-connect/auth
        token_url: https://nomad-lab.eu/fairdi/keycloak/auth/realms/fairdi_nomad_prod/protocol/openid-connect/token
        userdata_url: https://nomad-lab.eu/fairdi/keycloak/auth/realms/fairdi_nomad_prod/protocol/openid-connect/userinfo
  singleuser:
    podNameTemplate:

  prePuller:
    hook:
      enabled: false
